<?php
if (!defined('ABSPATH')) { exit; }

function home_spanish_translations(): array {
    return [
        'Primary navigation'=>'Navegación principal','Primary navigation — Spanish'=>'Navegación principal — Español','Primary navigation — English'=>'Navegación principal — Inglés','Footer navigation'=>'Navegación del pie',
        'HOME homepage'=>'Inicio de HOME','Practical advice for real life'=>'Consejos prácticos para la vida real','Search HOME'=>'Buscar en HOME','Explore HOME'=>'Explorar HOME','Menu'=>'Menú','Close menu'=>'Cerrar menú','Choose language'=>'Elegir idioma','Close language selector'=>'Cerrar selector de idioma','Language'=>'Idioma',
        'Cleaning'=>'Limpieza','Kitchen'=>'Cocina','Bathroom'=>'Baño','Laundry'=>'Lavandería','Appliances'=>'Electrodomésticos','Plumbing'=>'Fontanería','Pests'=>'Plagas','Heating & air'=>'Climatización','Home guide'=>'Guía del hogar',
        'Practical advice. Real solutions. A brighter home.'=>'Consejos prácticos. Soluciones reales. Un hogar mejor.','Home advice'=>'Consejos para el hogar','for real life.'=>'para la vida real.','Simple, trustworthy guidance for cleaning, fixing, maintaining and understanding the place you live — without turning every small problem into a project.'=>'Guías sencillas y fiables para limpiar, reparar, mantener y entender tu casa, sin convertir cada pequeño problema en un proyecto.','Explore all categories'=>'Explorar todas las categorías','See latest guides'=>'Ver las últimas guías',
        'What HOME stands for'=>'Lo que representa HOME','Trusted advice'=>'Consejos de confianza','Practical, reliable and easy to follow.'=>'Prácticos, fiables y fáciles de seguir.','A healthier home'=>'Un hogar más saludable','Small changes that make everyday life better.'=>'Pequeños cambios que mejoran el día a día.','Clear next steps'=>'Pasos claros','Know what to try, what to avoid and when to call.'=>'Sabe qué probar, qué evitar y cuándo pedir ayuda.',
        'Explore the house'=>'Explora la casa','Practical help for every corner of home.'=>'Ayuda práctica para cada rincón de casa.','Choose the area that needs attention. Each category brings together fixes, maintenance, cleaning and prevention.'=>'Elige la zona que necesita atención. Cada categoría reúne soluciones, mantenimiento, limpieza y prevención.',
        'Fresh from HOME'=>'Lo último en HOME','Featured guides & timely fixes.'=>'Guías destacadas y soluciones para el momento.','Read guide'=>'Leer guía','Published WordPress articles will appear here automatically.'=>'Los artículos publicados en WordPress aparecerán aquí automáticamente.','Also new'=>'También nuevo',
        'Make home feel easier'=>'Haz que cuidar la casa sea más fácil','One clear answer can save a lot of guessing.'=>'Una respuesta clara puede ahorrarte muchas dudas.','Search the HOME library whenever something leaks, smells, stops working, stains, clogs or simply needs a better routine.'=>'Busca en HOME cuando algo gotee, huela, deje de funcionar, se manche, se atasque o simplemente necesite una rutina mejor.',
        'Winter at home'=>'Invierno en casa','Keep heating working efficiently'=>'Mantén la calefacción funcionando de forma eficiente','Stay ahead of condensation and mold'=>'Anticípate a la condensación y al moho','Protect plumbing in cold weather'=>'Protege la fontanería del frío','Spring reset'=>'Puesta a punto de primavera','Build a room-by-room cleaning reset'=>'Haz una limpieza de primavera habitación por habitación','Close the door on seasonal pests'=>'Evita las plagas de temporada','Get cooling ready before hot days'=>'Prepara la climatización antes del calor','Summer at home'=>'Verano en casa','Keep rooms cooler and airflow moving'=>'Mantén las habitaciones frescas y el aire en movimiento','Handle warm-weather kitchen pests'=>'Controla las plagas de cocina típicas del calor','Help the fridge through hotter days'=>'Ayuda al frigorífico durante los días más calurosos','Fall home reset'=>'Puesta a punto de otoño','Check heating before colder weather'=>'Revisa la calefacción antes de que llegue el frío','Clean lint and dryer vent buildup'=>'Limpia la pelusa y el conducto de la secadora','Seal common pest entry points'=>'Sella los puntos habituales de entrada de plagas','A few useful things to check now.'=>'Algunas cosas útiles que conviene revisar ahora.',
        'A calmer home starts with a clear answer'=>'Un hogar más tranquilo empieza con una respuesta clara','Clear, practical guidance for the everyday problems that come with having a home.'=>'Guías claras y prácticas para los problemas cotidianos de tener una casa.','Explore'=>'Explorar','Around the house'=>'Por la casa','Useful answers. Calm explanations. Better homes.'=>'Respuestas útiles. Explicaciones claras. Mejores hogares.',
        'Browse HOME'=>'Explora HOME','No guides yet.'=>'Todavía no hay guías.','New household guides will appear here as they are published.'=>'Las nuevas guías del hogar aparecerán aquí a medida que se publiquen.','Results for “%s”'=>'Resultados para «%s»','No exact match.'=>'No hay coincidencias exactas.','Try fewer words or search for the symptom rather than the appliance or room.'=>'Prueba con menos palabras o busca el problema en lugar del electrodoméstico o la habitación.','What needs fixing, cleaning or checking?'=>'¿Qué necesitas reparar, limpiar o revisar?','Search'=>'Buscar',
        'HOME library'=>'Biblioteca HOME','Practical home guides'=>'Guías prácticas para el hogar','Clear answers for cleaning, repairs, appliances, pests and the everyday maintenance that keeps a home working.'=>'Respuestas claras sobre limpieza, reparaciones, electrodomésticos, plagas y el mantenimiento diario que hace que una casa funcione.','Nothing here yet.'=>'Todavía no hay contenido aquí.','Try a search or browse one of the household categories from the homepage.'=>'Prueba una búsqueda o explora una de las categorías del hogar desde la página de inicio.','Back to HOME'=>'Volver a HOME',
        'This room is empty.'=>'Esta página está vacía.','The page may have moved. Search HOME or head back to the homepage to find the right guide.'=>'La página puede haberse movido. Busca en HOME o vuelve al inicio para encontrar la guía adecuada.',
    ];
}

function home_translate_theme_string(string $translation, string $text, string $domain): string {
    if ($domain !== 'home' || home_is_english()) { return $translation; }
    $map=home_spanish_translations(); return $map[$text] ?? $translation;
}
add_filter('gettext','home_translate_theme_string',10,3);
